# Generated by Django 5.2.11 on 2026-02-17 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('shops', '0002_shop_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID (e.g., user@bank)', max_length=100)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name', max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='Account number', max_length=50)),
                ('ifsc_code', models.CharField(blank=True, help_text='IFSC code', max_length=20)),
                ('account_holder_name', models.CharField(blank=True, help_text='Account holder name', max_length=100)),
                ('qr_code', models.ImageField(blank=True, help_text='QR code image for payment', null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='shops.shop')),
            ],
        ),
    ]
