# Generated by Django 5.2.14 on 2026-07-01 05:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='WalletTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_source', models.CharField(choices=[('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('google_pay', 'Google Pay'), ('other', 'Other UPI App')], max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='accounts.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
