# Generated by Django 5.2.11 on 2026-02-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, help_text='Shop contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Shop contact number', max_length=15),
        ),
    ]
